### PR TITLE
translation

### PR DESCRIPTION
**Pull request by imkarimkarim**
i couldn't run the project on my locale machine because I'm a newbie to python but I try my best. i hope it will helps

### CODE REVIEW

**Comment by sbabashahi** [comment]
I will test it asap.

**Comment by sbabashahi** [comment]
I sent a pull request with lost configs to your repo, merge them and then add them to this pull request

**Comment by imkarimkarim** [comment]
> I sent a pull request with lost configs to your repo, merge them and then add them to this pull request

done :white_check_mark:

**Comment by yazdanv** [comment]
@imkarimkarim please make a pull request to develop branch, all merge requests to master branch would be closed

**Pull request closed without merging**
